const $=sel=>document.querySelector(sel);
// Use persistent browser storage when allowed; keep the demo functional on restricted file:// origins.
const storage=(()=>{try{const k='__ww_probe';window.localStorage.setItem(k,'1');window.localStorage.removeItem(k);return window.localStorage;}catch{const memory=new Map();return{getItem:k=>memory.has(k)?memory.get(k):null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k)};}})();
const safe=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={home:'<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>',assets:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',events:'<path d="M10 3h4M12 3v3M4 21V9l8-3 8 3v12z"/><path d="M9 13h6m-6 4h6"/>',evidence:'<path d="M5 3h11l3 3v15H5z"/><path d="M9 10h6m-6 4h6m-6 4h5"/>',arrow:'<path d="M5 12h14m-7-7 7 7-7 7"/>',drop:'<path d="M12 2c4 6 7 9.5 7 13a7 7 0 0 1-14 0c0-3.5 3-7 7-13z"/>',activity:'<path d="M3 12h4l3-8 4 16 3-8h4"/>',alert:'<path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v5m0 3v.01"/>',check:'<path d="m4 12 5 5L20 6"/>',zap:'<path d="m13 2-9 12h7l-1 8 10-12h-7l0-8z"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l4 3"/>',chevron:'<path d="m9 18 6-6-6-6"/>'};
const ic=(name,size=18)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.arrow}</svg>`;
const routes=[['home','현황','home'],['assets','설비','assets'],['events','이력','events'],['evidence','근거','evidence']];
const statusLabel=s=>s==='danger'?'확인 필요':s==='watch'?'주의':s==='unknown'?'데이터 없음':'정상';
const keys={power:'소비전력',flow:'유량',pressure:'압력',readiness:'점검 준비도',voltage:'전압',level:'수위',rise:'10분 상승량'};
const SID=()=>storage.getItem('wattguard-water-scenario')||'brazil';
let activeScenario=SCENARIOS.some(x=>x.id===SID())?SID():'brazil';
let evFilter='전체',evQuery='';
const db=()=>derive(activeScenario);
const activeRoute=()=>{const xs=decodeURIComponent((location.hash||'#/home').replace(/^#\/?/,'').replace(/^\//,'')).split('/').filter(Boolean);return xs.length?xs:['home'];};
function shell(html,section){const nav=routes.map(([route,label,icon])=>`<a href="#/${route==='home'?'home':route}" class="${section===route?'active':''}">${ic(icon)}<span>${label}</span></a>`).join('');return `<div class="root"><aside class="sidebar"><a href="#/home" class="brand"><small>SUAVEFORGE OPERATIONS</small><strong>WattGuard<span> /</span></strong><small>W A T E R</small></a><div class="navlabel">OPERATIONS</div><nav class="sidenav">${nav}</nav><div class="sidebar-bottom"><b>시연용 분석 환경</b>실제 펌프·SCADA 미연동<br>설비 제어 기능 없음<br>모든 수치와 알림은 합성 데이터</div><div class="copyright">© WattGuard Water · Prototype</div></aside><div class="workspace"><header class="topbar"><div class="top-left">WattGuard <span style="color:var(--teal)">WATER</span></div><div class="top-right"><span class="mode">● 시연 모드 · 합성 데이터</span><a href="#/evidence">근거 보기 ↗</a></div></header><main class="main">${html}</main><nav class="bottomnav" aria-label="메뉴">${nav}</nav></div></div>`}
function heading(title,subtitle,kicker='WATER INFRASTRUCTURE'){return `<div class="heading"><div><div class="kicker">${safe(kicker)}</div><h1>${title}</h1><p class="sub">${subtitle}</p></div><div class="ts">● 실제 설비 미연동 · 측정값은 가상</div></div>`;}
function scenarioPicker(s){return `<section class="scenario-strip"><div class="scenario-desc"><small>INTERACTIVE DEMO · 5가지 상황</small><strong>사고 사례를 참고한 가상 운전 상황을 선택하세요.</strong></div><label for="scenario" style="position:absolute;clip:rect(0,0,0,0)">시나리오 선택</label><select id="scenario" aria-label="시연 시나리오 선택">${SCENARIOS.map(x=>`<option value="${x.id}" ${x.id===s.id?'selected':''}>${safe(x.case)} | ${safe(x.title)}</option>`).join('')}</select></section>`;}
function badge(status){return `<span class="chip ${status}">${ic(status==='normal'?'check':'alert',13)} ${statusLabel(status)}</span>`;}
function mainNumber(a){const key=a.kind==='pump'?'power':a.kind==='generator'?'readiness':'level';return {val:fmt(a.values[key]),unit:a.units[key],name:keys[key]};}
function assetCard(a){const n=mainNumber(a);return `<a class="asset card" href="#/asset/${a.id}" aria-label="${safe(a.name)} ${statusLabel(a.status)} 상세"><div class="top"><div><div class="id">${safe(a.area)}</div><h3>${safe(a.name)}</h3></div>${badge(a.status)}</div><div class="focus">${n.val}<em>${n.unit}</em></div><div class="smallreason">${a.status==='normal'?'설비별 가상 기준 범위 내 작동':safe(a.difference)}</div><div class="foot"><span>${safe(n.name)} · ${a.id}</span><span>상세 확인 ${ic('arrow',12)}</span></div></a>`;}
function warningFoot(){return `<div class="note"><b>시연 데이터 안내</b> 이 화면의 센서값과 이상 경보는 개발·심사용으로 만든 가상 기록입니다. 실제 K-water 시설과 연결되지 않았으며, 위험 판정·제어·대피 명령에 사용할 수 없습니다. 연구 자료는 <a href="#/evidence">Evidence</a>에서 별도로 확인할 수 있습니다.</div>`;}
function scenariocaveat(s){return `<div class="scenario-safety"><div><strong style="color:var(--green)">${ic('check',14)} 이 시나리오에서 보여주는 것</strong><p>${safe(s.able)}</p></div><div><strong style="color:var(--red)">${ic('alert',14)} 실제로 입증하지 않은 것</strong><p>${safe(s.limit)}</p></div></div>`;}
function dashboard(){const m=db(),p=m.priority;return shell(`${heading('설비 이상을 먼저 확인합니다.','전력·가동·수위 신호를 비교해 점검이 필요한 설비를 한 화면에 표시합니다.')}${scenarioPicker(m.scenario)}<div class="summary"><section class="card hero ${p?'':'normal'}"><div class="herohead"><span class="eyebrow">전체 설비 상태 · 6개 설비</span>${badge(p?p.status:'normal')}</div><h2>${p?'점검이 필요한 설비가 있습니다.':'현재 시연 이상 신호가 없습니다.'}</h2><p>${p?`<b>${safe(p.name)}</b>에서 시연 규칙 <b>${p.rule}</b>에 해당하는 신호를 감지했습니다. 설비를 눌러 측정값과 판단 규칙을 함께 확인하세요.`:'모든 설비가 설정된 시연용 정상 범위에 있습니다. 시나리오를 바꾸면 이상 판정이 어떻게 달라지는지 확인할 수 있습니다.'}</p><div class="status-stack"><span class="chip danger">확인 필요 ${m.counts.danger}</span><span class="chip watch">주의 ${m.counts.watch}</span><span class="chip normal">정상 ${m.counts.normal}</span>${m.counts.unknown?`<span class="chip unknown">데이터 없음 ${m.counts.unknown}</span>`:''}</div><a class="btn primary" href="${p?'#/asset/'+p.id:'#/assets'}">${p?'이상 근거 바로 확인':'전체 설비 확인'} ${ic('arrow',15)}</a></section><section class="card priority"><div class="prio-top"><span class="label">점검 우선순위 · 01</span><span class="chip neutral">${m.scenario.case}</span></div><h3>${p?safe(p.name):'우선 점검 대상 없음'}</h3><p class="reason ${p?'':'none'}">${p?safe(p.reason):'현재 주의·확인 필요 신호가 없습니다.'}</p><p>${safe(m.scenario.explanation)}</p><a class="btn" href="${p?'#/asset/'+p.id:'#/events'}">${p?'측정 신호와 규칙 보기':'이력 확인'} ${ic('chevron',13)}</a></section></div><div class="three"><div class="card stat"><span class="label">확인 필요</span><div class="num" style="color:var(--red)">${m.counts.danger}</div><div class="desc">우선 확인 대상</div></div><div class="card stat"><span class="label">주의</span><div class="num" style="color:var(--amber)">${m.counts.watch}</div><div class="desc">추가 관찰 대상</div></div><div class="card stat"><span class="label">정상</span><div class="num" style="color:var(--green)">${m.counts.normal}</div><div class="desc">시연 기준 범위</div></div></div><div class="sectionhead"><h2>설비별 현재 상태</h2><span class="hint">카드를 누르면 판단 근거를 확인합니다</span></div><div class="assetgrid">${m.assets.map(assetCard).join('')}</div><div class="sectionhead"><h2>시나리오 판단 범위</h2><span class="hint">실제 사고 계측값이 아닙니다</span></div>${scenariocaveat(m.scenario)}${warningFoot()}`,'home');}
function assetsPage(){const m=db();return shell(`${heading('전체 설비','시설별 계측 신호와 점검 상태를 확인합니다.','ASSET MONITORING')}${scenarioPicker(m.scenario)}<div class="assetgrid">${m.assets.map(assetCard).join('')}</div>${warningFoot()}`,'assets');}
function chart(a){const {key,arr}=graphSeries(a,activeScenario);if(!arr.length)return `<p>데이터가 없습니다. 센서 연결을 확인하세요.</p>`;let nums=arr.flatMap(v=>[v.actual,v.baseline]),min=Math.min(...nums),max=Math.max(...nums);const buffer=Math.max(1,(max-min)*.17);min=Math.max(0,min-buffer);max+=buffer;const W=620,H=220,left=48,right=20,top=16,bottom=35;const x=i=>left+i/(arr.length-1)*(W-left-right);const y=v=>top+(max-v)/(max-min)*(H-top-bottom);const path=field=>arr.map((d,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(d[field]).toFixed(1)).join(' ');return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${safe(a.name)} ${safe(keys[key])} 시연 그래프" class="graph"><rect x="0" y="0" width="620" height="220" rx="10" fill="#fbfdfe"/>${Array.from({length:4},(_,i)=>{const yy=top+i*(H-top-bottom)/3;return `<line x1="48" y1="${yy}" x2="600" y2="${yy}" stroke="#e4eaee"/><text x="39" y="${yy+4}" text-anchor="end" font-size="11" fill="#738999">${fmt(max-i*(max-min)/3)}</text>`}).join('')}<path d="${path('baseline')}" fill="none" stroke="#88a5b5" stroke-width="2" stroke-dasharray="6 5"/><path d="${path('actual')}" fill="none" stroke="${a.status==='danger'?'#b83e38':a.status==='watch'?'#a85a13':'#087f8c'}" stroke-width="3.2" stroke-linecap="round"/><text x="48" y="208" fill="#7e93a0" font-size="11">이전</text><text x="600" y="208" text-anchor="end" fill="#7e93a0" font-size="11">현재</text></svg><div style="font-size:11px;color:var(--muted);display:flex;gap:17px"><span>― 실선: 가상 현재값</span><span>┄ 점선: 가상 기준값</span><span>※ 실제 이력 아님</span></div>`;}
function assetDetail(id){const m=db(),a=m.assets.find(x=>x.id===id);if(!a)return notFound();const n=mainNumber(a),ev=a.evidence?EVIDENCE.find(x=>x.id===a.evidence):null;const numbers=Object.keys(a.units).map(k=>`<div class="metric"><span>${safe(keys[k])}</span><strong>${fmt(a.values[k])}</strong><small>${safe(a.units[k])}</small></div>`);return shell(`${heading(a.name,`${a.area} · 계측 신호 상세 · 모든 수치는 가상입니다`,'ASSET DETAIL')}<div style="margin:-4px 0 15px"><a href="#/assets" style="font-size:12px;color:var(--teal);font-weight:750;text-decoration:none">← 설비 목록</a></div><div class="detailgrid"><div class="card detailbox"><div style="display:flex;justify-content:space-between;align-items:center;gap:9px;margin-bottom:18px"><span class="label">시연 상태 · ${a.id}</span>${badge(a.status)}</div><div class="metricrow">${numbers.join('')}</div><div class="sectionhead" style="margin:27px 0 4px"><h2>${safe(n.name)} 변화</h2><span class="hint">가상 시계열</span></div>${chart(a)}<div class="source"><div><strong>해당 설비와 같은 유형의 연구자료</strong><p>현재 시연 엔진의 실제 성능 검증 자료는 아닙니다.</p></div><a href="#/evidence">근거 보기 →</a></div></div><div class="card detailbox"><h2>왜 이 상태인가요?</h2><div class="label">판단 규칙 ${a.rule||'NORMAL'}</div><div class="rule-big">${safe(a.reason)}</div><div class="chip ${a.status}">${a.status==='normal'?'별도 점검 경고 없음':safe(a.difference)}</div><ul class="rule-list"><li>시나리오: ${safe(m.scenario.case)} · ${safe(m.scenario.title)}</li><li>상태 판정: ${statusLabel(a.status)}</li><li>비교 대상: 이 설비의 <b>가상 기준값</b></li><li>판정 방식: <b>시연용 결정 규칙</b> (현장 AI 학습·실증 미완료)</li><li>실제 명령 전송·장비 원격제어: <b>없음</b></li></ul>${ev?`<a class="btn primary" href="#/evidence/${ev.id}">판단 규칙 근거 확인 ${ic('arrow',15)}</a>`:`<a class="btn" href="#/evidence">연구·설계 근거 보기 ${ic('arrow',15)}</a>`}<div style="height:14px"></div><a class="btn" href="#/events">점검 이력에 확인 기록 남기기</a><div class="note"><b>주의:</b> ${safe(m.scenario.limit)}</div></div></div><div class="sectionhead"><h2>상황별 점검 범위</h2></div>${scenariocaveat(m.scenario)}${warningFoot()}`,'assets');}
function eventsPage(){const m=db();const key=`ww:ack:${m.scenario.id}`,ack=JSON.parse(storage.getItem(key)||'null');return shell(`${heading('이상·조치 이력','시연용 규칙이 표시한 확인 대상과 점검 기록입니다.','ALERT HISTORY')}${scenarioPicker(m.scenario)}<div class="timeline">${m.alerts.length?m.alerts.map(a=>`<article class="card event"><div><div style="display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin-bottom:7px">${badge(a.status)}<span class="label">${safe(a.rule)}</span></div><h3>${safe(a.name)} · ${safe(a.difference)}</h3><p>${safe(a.reason)}</p></div><a class="btn" href="#/asset/${a.id}">상세 보기 ${ic('arrow',15)}</a></article>`).join(''):`<div class="card empty">현재 시연 기준에서 발생한 이상 이력이 없습니다.</div>`}</div><div class="card detailbox" style="margin-top:18px"><h2>점검 확인 기록</h2><p class="muted">여기서 기록해도 설비 상태는 변경되지 않습니다. 원격 전송·제어가 아닌 현재 브라우저의 로컬 시연 기록입니다.</p>${ack?`<div class="source"><div><strong>기록 완료 · ${safe(ack.date)}</strong><p>${safe(ack.text)}</p></div><button class="btn" id="clearAck">기록 지우기</button></div>`:''}<form id="ackform" class="ackform"><label for="acktext" class="label">현장에서 확인할 사항을 기록해 보세요.</label><textarea id="acktext" maxlength="600" required placeholder="예: 전원공급 상태와 펌프 시험운전 가능 여부 확인 필요"></textarea><small>실제 담당자에게 전달되지 않습니다. 브라우저 저장소에만 저장됩니다.</small><div><button type="submit" class="btn primary">로컬 점검 기록 저장</button></div></form></div>${warningFoot()}`,'events');}
function evidencePage(){const cats=['전체',...new Set(EVIDENCE.map(x=>x.category))];const filtered=EVIDENCE.filter(e=>(evFilter==='전체'||e.category===evFilter)&&(`${e.title} ${e.claim} ${e.publisher} ${e.applies_to.join(' ')}`.toLowerCase().includes(evQuery.toLowerCase())));return shell(`${heading('Evidence Registry','실제 보도·연구 결과와 앱 내부 판단 규칙을 구분해 공개합니다.','TRACEABLE EVIDENCE')}<div class="evid-controls"><input id="evSearch" aria-label="근거 검색" placeholder="사고·연구·규칙 검색" value="${safe(evQuery)}">${cats.map(x=>`<button type="button" class="${x===evFilter?'active':''}" data-evfilter="${safe(x)}">${safe(x)}</button>`).join('')}</div><p class="sub" style="margin-bottom:14px">등록 근거 ${filtered.length} / ${EVIDENCE.length}건 · 외부 출처 링크와 제품 적용 범위를 별도 표기합니다.</p><div class="evidlist">${filtered.length?filtered.map(e=>`<a href="#/evidence/${e.id}" class="card evidence"><span class="evtag">${safe(e.category)} · ${safe(e.scope)}</span><h3>${safe(e.title)}</h3><p>${safe(e.claim)}</p><div class="metaline"><span>${safe(e.publisher)} · ${e.year}</span><b>내용 확인 →</b></div></a>`).join(''):`<div class="card empty">검색 결과가 없습니다.</div>`}</div>${warningFoot()}`,'evidence');}
function evidenceDetail(id){const e=EVIDENCE.find(x=>x.id===id);if(!e)return notFound();return shell(`${heading('근거 상세',`등록 ID ${e.id} · ${e.category}`,'EVIDENCE DETAIL')}<div style="margin:-4px 0 15px"><a href="#/evidence" style="font-size:12px;color:var(--teal);font-weight:750;text-decoration:none">← Evidence 목록</a></div><article class="card detailbox" style="max-width:850px"><span class="evtag">${safe(e.category)} · ${safe(e.scope)}</span><h2 style="font-size:23px;margin:15px 0 10px;line-height:1.4">${safe(e.title)}</h2><p class="sub">${safe(e.publisher)} · ${e.year} · ${safe(e.source_type)}</p><div class="evfield"><strong>출처가 뒷받침하는 사실</strong><p>${safe(e.claim)}</p></div><div class="evfield"><strong>이 앱에는 어떻게 적용했나?</strong><p>${safe(e.product_implication)}</p></div><div class="evfield"><strong>해석의 한계 · 주장 금지선</strong><p>${safe(e.limitations)}</p></div><div class="evfield"><strong>연결된 분석 규칙</strong><p>${e.applies_to.map(safe).join(' · ')}</p></div><div style="display:flex;flex-wrap:wrap;gap:11px;margin-top:18px">${e.url?`<a class="btn primary" href="${safe(e.url)}" target="_blank" rel="noopener noreferrer">원문 열기 ↗</a>`:`<span class="chip neutral">제품 내부 규칙 · 외부 원문 없음</span>`}<a href="#/evidence" class="btn">근거 목록으로</a></div></article>${warningFoot()}`,'evidence');}
function notFound(){return shell(`${heading('페이지를 찾을 수 없습니다.','주소가 올바른지 확인하고 현황 페이지로 돌아가세요.','NOT FOUND')}<a class="btn primary" href="#/home">현황으로 돌아가기</a>`,'home');}
function render(){const xs=activeRoute();let html;if(xs[0]==='home')html=dashboard();else if(xs[0]==='assets')html=assetsPage();else if(xs[0]==='asset'&&xs[1])html=assetDetail(xs[1]);else if(xs[0]==='events')html=eventsPage();else if(xs[0]==='evidence'&&xs[1])html=evidenceDetail(xs[1]);else if(xs[0]==='evidence')html=evidencePage();else html=notFound();$('#app').innerHTML=html;document.title=`WattGuard Water | ${xs[0]==='home'?'현황':xs[0]==='asset'?'설비 상세':xs[0]==='evidence'?'Evidence':xs[0]==='events'?'이력':'설비'}`;
 $('#scenario')?.addEventListener('change',e=>{activeScenario=e.target.value;storage.setItem('wattguard-water-scenario',activeScenario);render();});
 document.querySelectorAll('[data-evfilter]').forEach(b=>b.addEventListener('click',()=>{evFilter=b.dataset.evfilter;render();}));
 $('#evSearch')?.addEventListener('input',e=>{const cursor=e.target.selectionStart;evQuery=e.target.value;render();const input=$('#evSearch');input.focus();input.setSelectionRange(cursor,cursor);});
 $('#ackform')?.addEventListener('submit',e=>{e.preventDefault();const value=$('#acktext').value.trim();if(!value)return;storage.setItem(`ww:ack:${activeScenario}`,JSON.stringify({text:value,date:new Date().toLocaleString('ko-KR')}));render();});
 $('#clearAck')?.addEventListener('click',()=>{storage.removeItem(`ww:ack:${activeScenario}`);render();});
}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});render();
